encoding_dir: /home/zhichaog/encoding/
encoding_types:
  - doc-v2-distill
  - v2-distill
beir_datasets:
  - trec-covid
  - nfcorpus
  - nq
  - hotpotqa
  - fiqa
  - arguana
  - webis-touche2020
  - dbpedia-entity
  - scidocs
  - fever
  - climate-fever
  - scifact
  - quora
pruning:
  ingest:
    - pruning_type: max_ratio
      pruning_number: [0,0.1,0.15,0.2,0.3,0.4]
    - pruning_type: abs_value
      pruning_number: [0.1,0.2,0.3,0.4,0.5]
    - pruning_type: alpha_mass
      pruning_number: [0.9,0.8,0.7,0.6,0.5]
    - pruning_type: top_k
      pruning_number: [256,128,64,48,32]
  search:
    - pruning_type: max_ratio
      pruning_number: [0,0.1,0.15,0.2,0.3,0.4]
    - pruning_type: abs_value
      pruning_number: [0.1,0.2,0.3,0.4,0.5]
    - pruning_type: alpha_mass
      pruning_number: [0.9,0.8,0.7,0.6,0.5]
    - pruning_type: top_k
      pruning_number: [256,128,64,48,32]
result_dir: results